os: Visual Studio 2015
version: '{branch}.0.{build}'
build_script:
  - build.cmd
clone_depth: 1
test: off
deploy: off
artifacts:
  - path: src\NetCore.Simple.Extensions/bin/Release*.nupkg
    name: NetCore.Simple.Extensions